"""Streamlit dashboard for the Q-Commerce ML Pipeline.

Run: streamlit run dashboard/app.py
"""
import json
import sys
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import streamlit as st
import plotly.express as px

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from src.ml_pipeline.config import (
    CLEAN_DATA_DIR, MODELS_DIR, FIGURES_DIR, REPORTS_DIR,
)

st.set_page_config(
    page_title="Q-Commerce Price Intelligence",
    page_icon="🛒",
    layout="wide",
)


@st.cache_data
def load_data(tag="blinkit"):
    path = CLEAN_DATA_DIR / f"{tag}_clean.parquet"
    if not path.exists():
        return None
    return pd.read_parquet(path)


@st.cache_data
def load_clustered(tag="blinkit"):
    path = CLEAN_DATA_DIR / f"{tag}_clustered.parquet"
    if not path.exists():
        return None
    return pd.read_parquet(path)


@st.cache_resource
def load_price_model():
    path = MODELS_DIR / "rf_price_model.joblib"
    return joblib.load(path) if path.exists() else None


@st.cache_resource
def load_discount_model():
    path = MODELS_DIR / "rf_discount_classifier.joblib"
    return joblib.load(path) if path.exists() else None


@st.cache_data
def load_metrics():
    path = REPORTS_DIR / "metrics.json"
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f)


df = load_data()
df_clustered = load_clustered()
price_model = load_price_model()
discount_model = load_discount_model()
metrics = load_metrics()

if df is None:
    st.error("No cleaned data found. Run `python pipeline.py` first.")
    st.stop()

st.title("🛒 Q-Commerce Price Intelligence Dashboard")
st.caption("Machine-learning analysis of a Q-Commerce product catalog — built on a reusable pipeline")

with st.sidebar:
    st.header("📊 Snapshot")
    st.metric("Total products", f"{len(df):,}")
    st.metric("Unique brands", f"{df['brand'].nunique():,}")
    st.metric("Categories", f"{df['category'].nunique():,}")
    st.metric("Mean discount", f"{df['discount_pct'].mean():.1f}%")
    st.metric("Out of stock", f"{df['is_oos'].mean()*100:.1f}%")
    st.divider()
    st.caption("**Pipeline**: data → clean → features → EDA → RF Price → RF Discount → KMeans")

tab_overview, tab_eda, tab_price, tab_discount, tab_clusters, tab_pipeline = st.tabs(
    ["📈 Overview", "🔍 EDA", "💰 Price Predictor", "🏷️ Discount Insights", "🎯 Clusters", "⚙️ Pipeline"]
)

with tab_overview:
    st.subheader("Dataset at a glance")
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Products", f"{len(df):,}")
    c2.metric("Median price", f"Rs.{df['price'].median():.0f}")
    c3.metric("% on discount", f"{df['is_discounted'].mean()*100:.1f}%")
    c4.metric("Avg rating", f"{df['rating'].mean():.2f}")

    st.divider()
    st.subheader("Top 10 categories by product count")
    cat_counts = df["category"].value_counts().head(10).reset_index()
    cat_counts.columns = ["category", "count"]
    fig = px.bar(cat_counts, x="count", y="category", orientation="h",
                 color="count", color_continuous_scale="Blues")
    fig.update_layout(yaxis={"categoryorder": "total ascending"}, height=400)
    st.plotly_chart(fig, use_container_width=True)

    c1, c2 = st.columns(2)
    with c1:
        st.subheader("Discount % distribution")
        fig = px.histogram(df, x="discount_pct", nbins=40, color_discrete_sequence=["#10b981"])
        fig.add_vline(x=df["discount_pct"].median(), line_dash="dash", line_color="red",
                      annotation_text=f"Median {df['discount_pct'].median():.0f}%")
        st.plotly_chart(fig, use_container_width=True)
    with c2:
        st.subheader("Price distribution (log)")
        fig = px.histogram(df, x="price", nbins=60, log_x=True, color_discrete_sequence=["#3b82f6"])
        st.plotly_chart(fig, use_container_width=True)

with tab_eda:
    st.subheader("Exploratory data analysis")
    st.caption("Charts auto-generated by the pipeline. Add a new dataset and re-run — these refresh.")
    figs = sorted(FIGURES_DIR.glob("*.png"))
    eda_figs = [f for f in figs if not f.name.startswith(("rf_", "discount_classifier_", "kmeans_"))]
    cols = st.columns(2)
    for i, f in enumerate(eda_figs):
        with cols[i % 2]:
            st.image(str(f), caption=f.stem.replace("_", " ").title(), use_container_width=True)

    st.divider()
    st.subheader("Numeric correlations (interactive)")
    num_cols = ["price", "mrp", "discount_pct", "unit_value", "rating", "inventory"]
    num_cols = [c for c in num_cols if c in df.columns]
    corr = df[num_cols].corr().round(2)
    fig = px.imshow(corr, text_auto=True, aspect="auto", color_continuous_scale="RdBu_r",
                    zmin=-1, zmax=1)
    st.plotly_chart(fig, use_container_width=True)

with tab_price:
    st.subheader("Random Forest — price predictor")
    if price_model is None:
        st.warning("Price model not found. Run `python pipeline.py`.")
    else:
        pm = metrics.get("price_model", {})
        c1, c2, c3 = st.columns(3)
        c1.metric("R² (held-out)", f"{pm.get('r2', 0):.3f}")
        c2.metric("MAE", f"Rs.{pm.get('mae', 0):.0f}")
        c3.metric("RMSE", f"Rs.{pm.get('rmse', 0):.0f}")

        c1, c2 = st.columns(2)
        with c1:
            st.image(str(FIGURES_DIR / "rf_predicted_vs_actual.png"), use_container_width=True)
        with c2:
            st.image(str(FIGURES_DIR / "rf_feature_importance.png"), use_container_width=True)
        st.image(str(FIGURES_DIR / "rf_residuals.png"), use_container_width=True)

        st.divider()
        st.subheader("🎛️ Try the model")
        st.caption("Pick product attributes and the trained RF predicts a price.")
        colA, colB, colC = st.columns(3)
        with colA:
            mrp = st.number_input("MRP (Rs.)", min_value=1.0, value=200.0, step=10.0)
            unit_value = st.number_input("Unit value", min_value=0.0, value=500.0, step=10.0)
            rating = st.slider("Rating", 1.0, 5.0, 4.4, 0.05)
        with colB:
            inventory = st.number_input("Inventory", min_value=0, value=5)
            unit_type = st.selectbox("Unit type", sorted(df["unit_type"].unique()))
            category = st.selectbox("Category", sorted(df["category"].unique()))
        with colC:
            top_brands = ["unbranded"] + df["brand"].value_counts().head(50).index.tolist()
            brand = st.selectbox("Brand", top_brands)
            is_multipack = st.checkbox("Multi-pack?", False)

        if st.button("Predict price", type="primary"):
            row = pd.DataFrame([{
                "mrp": mrp, "unit_value": unit_value, "rating": rating,
                "inventory": inventory, "is_multipack": int(is_multipack),
                "is_unbranded": int(brand == "unbranded"),
                "price_per_unit": mrp / max(unit_value, 1),
                "log_mrp": np.log1p(mrp),
                "unit_type": unit_type, "category": category, "brand": brand,
            }])
            pred = price_model.predict(row)[0]
            implied_disc = (mrp - pred) / mrp * 100
            c1, c2 = st.columns(2)
            c1.metric("Predicted selling price", f"Rs.{pred:.2f}")
            c2.metric("Implied discount", f"{implied_disc:.1f}%")

with tab_discount:
    st.subheader("Random Forest — high-discount classifier")
    st.caption(f"Target: discount ≥ 15%. {df['is_high_discount'].mean()*100:.1f}% of products meet this.")
    if discount_model is None:
        st.warning("Classifier not found. Run `python pipeline.py`.")
    else:
        dm = metrics.get("discount_classifier", {})
        c1, c2, c3 = st.columns(3)
        c1.metric("Accuracy", f"{dm.get('accuracy', 0)*100:.1f}%")
        c2.metric("F1 score", f"{dm.get('f1', 0):.3f}")
        c3.metric("ROC AUC", f"{dm.get('roc_auc', 0):.3f}")

        c1, c2 = st.columns(2)
        with c1:
            st.image(str(FIGURES_DIR / "discount_classifier_confusion.png"), use_container_width=True)
        with c2:
            st.image(str(FIGURES_DIR / "discount_classifier_roc.png"), use_container_width=True)

        st.divider()
        st.subheader("Highest-discount products in catalog")
        cols = ["product_name", "brand", "category", "price", "mrp", "discount_pct", "rating"]
        cols = [c for c in cols if c in df.columns]
        st.dataframe(df.sort_values("discount_pct", ascending=False).head(20)[cols],
                     use_container_width=True)

with tab_clusters:
    st.subheader("KMeans — product segmentation")
    st.caption("Unsupervised grouping of products by price, MRP, discount, unit, rating, inventory.")
    cm = metrics.get("clusters", {})
    sizes = cm.get("cluster_sizes", {})
    cols = st.columns(len(sizes) if sizes else 1)
    for i, (cid, n) in enumerate(sorted(sizes.items(), key=lambda x: -x[1])):
        cols[i].metric(f"Cluster {cid}", f"{n:,} products")

    c1, c2 = st.columns(2)
    with c1:
        st.image(str(FIGURES_DIR / "kmeans_clusters_pca.png"), use_container_width=True)
    with c2:
        st.image(str(FIGURES_DIR / "kmeans_cluster_profiles.png"), use_container_width=True)

    if df_clustered is not None:
        st.divider()
        st.subheader("Browse cluster")
        chosen = st.selectbox("Pick a cluster", sorted(df_clustered["cluster"].unique()))
        sub = df_clustered[df_clustered["cluster"] == chosen]
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Size", f"{len(sub):,}")
        c2.metric("Mean price", f"Rs.{sub['price'].mean():.0f}")
        c3.metric("Mean discount", f"{sub['discount_pct'].mean():.1f}%")
        c4.metric("Mean rating", f"{sub['rating'].mean():.2f}")
        cols = ["product_name", "brand", "category", "price", "mrp", "discount_pct"]
        cols = [c for c in cols if c in sub.columns]
        st.dataframe(sub.head(50)[cols], use_container_width=True)

with tab_pipeline:
    st.subheader("Reusable pipeline")
    st.markdown("""
**Drop in any Q-commerce CSV with the same schema (Zepto, Instamart, BigBasket) and re-run:**
```bash
python pipeline.py --input data/zepto_export.csv --tag zepto
streamlit run dashboard/app.py
```

The pipeline auto-handles:
- Schema validation (errors out cleanly on missing columns)
- Constant-column drop (auto-detected)
- Type coercion + empty-string → null
- Product deduplication on `product_id`
- Multi-pack unit parsing (`"x 200 g"` → 200g × pack count)
- Rare unit-type bucketing
- Rating median imputation
- Brand `""` → `"unbranded"`
- Feature engineering: `discount_pct`, `is_discounted`, `is_high_discount`, `price_per_unit`, `log_price`, `is_oos`, `category`, `is_unbranded`
- All EDA charts above
- Three trained models with metrics & graphs
""")
    st.divider()
    st.subheader("Pipeline metrics (last run)")
    st.json(metrics)
